### ISSUE TITLE
[Question] Any guide on how to use this ?

### ISSUE THREAD

**Issue by Akianonymus** [bageljrkhanofemus/autoimport-core#2]

**Comment by bagel897** [comment]
1. Its still a work in progress. I may rewrite it in rust.
2. Its a fork of the rope-autoimport code which I wrote. There's documentation on rope on how to use it in an editor/IDE
3. The only know editor/IDE integration for that is my PR for pylsp. https://github.com/python-lsp/python-lsp-server/pull/199.
4. When this is ready, I'll have docs *somewhere*
